services:
  slskd:
    image: slskd/slskd
    network_mode: host
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./slskd-data:/app
      - /mnt/data/slskd/downloads:/app/downloads
    ports:
      - "5030:5030"
