services:
  slskd:
    image: slskd/slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./slskd-data:/app
      - /mnt/data/slskd/downloads:/app/downloads
      - /mnt/data/music:/music
    ports:
      - "5030:5030"
      - "50400:50300"
